# ===================================================================
# Spring Boot configuration for the "staging" profile.
# This configuration overrides the application.yml file.
# ===================================================================

logging:
  s3:
    bucket: peecko-api-logs-435496007267-eu-central-1-an
    prefix: staging/
    region: eu-central-1
  level:
    ROOT: INFO
    com.peecko.api: DEBUG
    org.springframework: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    org.hibernate.sql: WARN
    org.hibernate.type.descriptor.sql: WARN

management:
  prometheus:
    metrics:
      export:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  jpa:
    properties:
      hibernate:
        default_schema: pwa
  datasource:
    url: jdbc:postgresql://pwa-rds-dev.cvswuu602c9n.eu-central-1.rds.amazonaws.com:5432/postgres?currentSchema=pwa
    username: pwa_app
    password: pwa-app-100$
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.office365.com
    port: 587
    username: info@peecko.com
    password: InfoPeecko@2022
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  thymeleaf:
    cache: true
  web:
    resources:
      cache:
        period: 0

server:
  port: 8081
  address: 127.0.0.1
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

app:
  api:
    jwtSecret: peeckoSecretKey
    jwtExpirationMs: 36000000
